### ISSUE TITLE
Has 32bit abis been dropped?

### ISSUE THREAD

**Issue by sonoro1234** [luapower/pthread#6]
Hi Cosmin,

If I understand correctly, commit https://github.com/luapower/pthread/commit/55c64d0b2d6a5e1f87c194ab57e7acdb9601b918 dropped 32bit abi. Is that true? Which are the reasons?

Best

Victor Bombi

**Comment by capr** [comment]
Hi Victor, it's the same reasons for dropping OSX support. Since I'm the only maintainer, I have to prioritize my efforts, and spending my time on writing useful functionality is better for me than doing boring grunt work. Besides if you really need 32bit binaries, you can get the build scripts back from git history and build them yourself.

**Comment by sonoro1234** [comment]
I understand the reasons. I am not interested in binarys but in ffi definitions. As it was already done and working ok (at least for me) perhaps it would had been better to just keep it saying you cant take care of 32bit abis.

**Comment by capr** [comment]
Bear in mind that luapower modules don't work on just any 32bit platform (like eg. RPI), they only work for desktops and 32bit deskops are virtually non-existent today.

**Comment by sonoro1234** [comment]
But I am doing 32bit compilations to be executed on 64bit windows

**Comment by capr** [comment]
why?

**Comment by sonoro1234** [comment]
To discriminate 64bit LuaJIT issues from 32bit issues.
To test performance differences also.
